### ISSUE TITLE
Design webpage color scheme

### ISSUE THREAD

**Issue by wendybaum** [wendybaum/Bookly#26]
## User Story

As a user I want to visit websites that are aesthetically pleasing.

## Acceptance Criteria

- [x] Use at least one base and one accent color, but no more than three

**Comment by rfinkley** [comment]
Please let me know what you think of this design. The major difference is the use of cards instead of populating the data retrieved from GoodReads and Open Library as cards instead of as a table. Let me know if you think that's possible.

![image](https://user-images.githubusercontent.com/46961208/73613850-a4910f80-45c7-11ea-9dcc-95645c0357b7.png)
